### PR TITLE
Updated for python 3

### PR DESCRIPTION
**Pull request by benthayer**
I was using this for a project and needed it for python3, so I figured I'd make a pull request so you could update it on pypi, if you cared enough to.

### CODE REVIEW

**Comment by Fantomas42** [comment]
Hello,

thank you for your pull-request,
unfortunately in this state I cannot directly merge it,
because the support for Python 2 is now broken.

https://travis-ci.org/Fantomas42/sudoku-solver/builds/213119560

I will see if I can fix it.

If you don't mind, on what kind of project to you use this library ?

Regards

**Comment by benthayer** [comment]
I am attempting to write a neural network that learns to solve sudoku, and I needed many training examples. I found a collection of 2000 unsolved sudoku puzzles, so I used this to solve them and now I have training solutions. Tensorflow requires python 3.5 and I wanted to keep all the code in the same repo, so I just converted it.

**Comment by benthayer** [comment]
I'll be committing later today, I can share the link with you when I do

**Comment by Fantomas42** [comment]
Okay I have a fix, I will make a new release soon.

**Pull request merged**
